app/applications/products/urls.py
from django.urls import path

from applications.products import views

app_name = 'products'

urlpatterns = [
    path('', views.products_list_ru, name='product-list-ru'),
    path('kg/', views.products_list_kg, name='product-list-kg'),
    path('en/', views.products_list_en, name='product-list-en'),
    path('send_email/', views.send_email, name='send_mail'),
    path('send_number/', views.send_number, name='send_number'),
    path('products/<int:product_id>/', views.product_details_ru, name='product-details'),
    path('products/kg/<int:product_id>/', views.product_details_kg, name='product-details-kg'),
    path('products/en/<int:product_id>/', views.product_details_en, name='product-details-en'),
]

app/devala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('applications.products.urls', namespace='product')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/applications/products/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    title_ru = models.CharField(max_length=50, default='qwerty')
    title_en = models.CharField(max_length=50, default='qwerty')
    title_kg = models.CharField(max_length=50, default='qwerty')
    short_description_ru = models.TextField(max_length=100, default='qwerty')
    short_description_kg = models.TextField(max_length=100, default='qwerty')
    short_description_en = models.TextField(max_length=100, default='qwerty')
    full_description_ru = models.TextField(default='qwerty')
    full_description_en = models.TextField(default='qwerty')
    full_description_kg = models.TextField(default='qwerty')
    image = models.ImageField(upload_to='images')

    def __unicode__(self):
        return self.title_ru + self.title_en + self.title_kg

    def __str__(self):
        return self.title_ru + self.title_en + self.title_kg

    def get_absolute_url(self):
        return reverse('product:product-details', args=[self.id])


class SendEmail(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=50, blank=True)
    number = models.CharField(max_length=20)
    email_message = models.TextField(blank=True)
    created = models.DateTimeField(auto_now=True)

app/applications/products/forms.py
from django import forms
from .models import SendEmail


class SendEmailForm(forms.ModelForm):
    class Meta:
        model = SendEmail
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': u'Имя', 'class': 'form-control name'}),
            'email': forms.TextInput(attrs={'placeholder': u'Email', 'class': 'form-control email'}),
            'number': forms.TextInput(attrs={'placeholder': u'Номер телефона', 'class': 'form-control number'}),
            'email_message': forms.Textarea(attrs={'placeholder': u'Сообщение', 'class': 'form-control message'}),
        }


class SendEmailKGForm(forms.ModelForm):
    class Meta:
        model = SendEmail
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': u'Аты', 'class': 'form-control name'}),
            'email': forms.TextInput(attrs={'placeholder': u'Email', 'class': 'form-control email'}),
            'number': forms.TextInput(attrs={'placeholder': u'Телефон', 'class': 'form-control number'}),
            'email_message': forms.Textarea(attrs={'placeholder': u'Текст', 'class': 'form-control message'}),
        }


class SendEmailENForm(forms.ModelForm):
    class Meta:
        model = SendEmail
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': u'Name', 'class': 'form-control name'}),
            'email': forms.TextInput(attrs={'placeholder': u'Email', 'class': 'form-control email'}),
            'number': forms.TextInput(attrs={'placeholder': u'Number', 'class': 'form-control number'}),
            'email_message': forms.Textarea(attrs={'placeholder': u'Message', 'class': 'form-control message'}),
        }

app/applications/products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from applications.certificates.models import Certificate
from applications.partners.models import Partner
from .models import Product
from .forms import SendEmailForm, SendEmailKGForm, SendEmailENForm
from django.views.decorators.http import require_POST
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from applications.products.tasks import send_user_email
import threading


def products_list_ru(request):
    products = Product.objects.all()
    partners = Partner.objects.all()
    certificates = Certificate.objects.all()
    form = SendEmailForm()
    return render(request, 'index.html', locals())


def products_list_kg(request):
    products = Product.objects.all()
    partners = Partner.objects.all()
    certificates = Certificate.objects.all()
    form = SendEmailKGForm()
    return render(request, 'index_kg.html', locals())


def products_list_en(request):
    products = Product.objects.all()
    partners = Partner.objects.all()
    certificates = Certificate.objects.all()
    form = SendEmailENForm()
    return render(request, 'index_en.html', locals())


def product_details_ru(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'products/details.html', {
        'product': product,
    })


def product_details_en(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'products/details_en.html', {
        'product': product,
    })


def product_details_kg(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'products/details_kg.html', {
        'product': product,
    })


@require_POST
def send_email(request):
    form = SendEmailENForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        number = form.cleaned_data['number']
        email_message = form.cleaned_data['email_message']
        message = '{message}. {user}, {email}, {number}'.format(message=email_message, user=name, email=email, number=number)
        send_user_email.delay('Заявка', message, email)
        # thr = threading.Thread(target=send_user_email, args=(u'Заявка', message, ''))
        # thr.start()
        return JsonResponse({'response': 'Ваши данные успешно отправлены на сервер'})
    return JsonResponse({'response': 'Error', 'error': form.errors})


@require_POST
def send_email_kg(request):
    form = SendEmailKGForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        number = form.cleaned_data['number']
        email_message = form.cleaned_data['email_message']
        message = '{message}. {user}, {email}, {number}'.format(message=email_message, user=name, email=email, number=number)
        send_user_email.delay('Заявка', message, email)
        # thr = threading.Thread(target=send_user_email, args=(u'Заявка', message, ''))
        # thr.start()
        return JsonResponse({'response': 'Ваши данные успешно отправлены на сервер'})
    return JsonResponse({'response': 'Error', 'error': form.errors})


@require_POST
def send_number(request):
    number = request.POST['number']
    if len(number) == 10:
        message = u'Посетитель сайта с номером {number} попросил Вас перезвонить ему'.format(number=number)
        thr = threading.Thread(target=send_user_email, args=(u'Заявка на звонок', message, ''))
        thr.start()

        return JsonResponse({'response': u'Ваша заявка отправлена'})
    return JsonResponse({'response': u'Error', 'error': u'Номер введен неверно'})

app/templates/products/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.title_ru}}</title>
    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fancybox-3.0/dist/jquery.fancybox.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'responsive/main_responsive.css' %}">
    <script src="{% static 'fancybox-3.0/dist/jquery.fancybox.min.js' %}"></script>
</head>
<body class="details">
<div>
<div class="container-fluid hat compensate-for-scrollbar">
    <div class="row">
        <a href="{% url 'product:product-list-ru' %}#products">
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-3 col-xl-3 text-center">
                <p class="shapka">
                    <span>
                        <i class="fa fa-chevron-left" aria-hidden="true"></i>
                        Назад
                    </span>
                </p>
            </div>
        </a>
        <div class="col-xs-5 col-sm-4 col-md-6 col-lg-6 col-xl-6 text-center">
{#            <img src="{% static 'img/devala.png' %}" height="40" width="auto" >#}
        </div>
        <div class="col-xs-7 col-sm-4 col-md-3 col-lg-3 col-xl-3 text-center"><i></i>
            <p class="shapka">
                <span>
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    0505040717
                </span>
            </p>
        </div>
    </div>
</div>

<div class="container-fluid product_main">
    <div class="row sotka">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2 col-xl-8 col-xl-offset-2 product_main_block">
            <div class="col-sm-12 col-md-4 picture">
                <a data-fancybox="single" class="fancybox" href="/mediafiles/{{ product.image }}">
                    <img class="center-block" src="{% if product.image %}/mediafiles/{{ product.image}}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
                </a>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-8 title_desc">

                <p class="zagolovok">{{ product.title_ru }}</p>
                <hr>
                <p id="interes">Заинтересовал товар? Оставьте свой номер и мы Вам перезвоним</p>
                <div class="zakaz_zvonka">
                    <p id="hata"></p>
                    <form method="post" action="{% url 'product:send_number' %}" id="myForm">
                        {% csrf_token %}
                        <input class="nomer" name="number" placeholder="0555123456">
                        <button class="otpravka" type="submit">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid product_second">
    <div class="row sotka">
        <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 product_second_block">
            <p>{{ product.full_description_ru| safe | linebreaks }}</p>

            <a href="{% url 'product:product-list-ru' %}#products">
                <span class="visible-xs" id="for_tel">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i>
                    Назад
                </span>
            </a>
        </div>
    </div>
</div>

<div class="container-fluid footer">
    <div class="row">
        <div class="text-center">
            <div class="col-md-4">
                <p>
                    <span>
                        <i class="fa fa-map-marker mesto" aria-hidden="true"></i>
                    </span>
                    ул. Тыныстанова 197
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <span id="cep">                         <i class="fa fa-phone-square"></i>                         + 996 505 04 07 17<br/> 		        <i class="fa fa-whatsapp" style="color:#25d366"></i> 		        + 90 507 728 66 86                     </span>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <span>
                        Мы в социальных сетях:
                        <i class="fa fa-facebook"></i>
                        <i class="fa fa-instagram"></i>
                    </span>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid rights">
    <div class="row">
        <div class="col-md-12">
            <p>&#169; 2020 DEVALA. Все права защищены</p>
        </div>
    </div>
</div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close text-center" data-dismiss="modal">&times;</button>

      </div>
      <div class="modal-body text-center">
        <h4 class="modal-title">Ваш номер успешно отправлен!</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript" src="{% static 'js/ajaxform.js' %}"></script>
<script>
    $(document).ready(function() {
            // bind 'myForm' and provide a simple callback function
            $('#myForm').ajaxForm(function(response) {
                console.log(response);
                if (response['error']) {
                    $('input').addClass('has-errors');
                    $('#hata').html('Номер введен неверно').slideUp().slideDown();
                }
                else {
                    $('input:not([name="csrfmiddlewaretoken"])').val('');
                    $('#hata').css('display', 'none').html('');
                    $('input').removeClass('has-errors');
                    $('#myModal').modal();
                }
            });
        });
</script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- BEGIN JIVOSITE CODE {literal} --> <script type='text/javascript'> (function(){ var widget_id = '9a3knLkEuT';var d=document;var w=window;function l(){ var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);}if(d.readyState=='complete'){l();}else{if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();</script> <!-- {/literal} END JIVOSITE CODE -->
</body>
</html>

app/templates/products/details_en.html
details.html{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.title_en }}</title>
    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fancybox-3.0/dist/jquery.fancybox.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'responsive/main_responsive.css' %}">
    <script src="{% static 'fancybox-3.0/dist/jquery.fancybox.min.js' %}"></script>
</head>
<body class="details">
<div>
<div class="container-fluid hat compensate-for-scrollbar">
    <div class="row">
        <a href="{% url 'product:product-list-en' %}#products">
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-3 col-xl-3 text-center">
                <p class="shapka">
                    <span>
                        <i class="fa fa-chevron-left" aria-hidden="true"></i>
                        Back
                    </span>
                </p>
            </div>
        </a>
        <div class="col-xs-5 col-sm-4 col-md-6 col-lg-6 col-xl-6 text-center">
{#            <img src="{% static 'img/devala.png' %}" height="40" width="auto" >#}
        </div>
        <div class="col-xs-7 col-sm-4 col-md-3 col-lg-3 col-xl-3 text-center"><i></i>
            <p class="shapka">
                <span>
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    0505040717
                </span>
            </p>
        </div>
    </div>
</div>

<div class="container-fluid product_main">
    <div class="row sotka">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2 col-xl-8 col-xl-offset-2 product_main_block">
            <div class="col-sm-12 col-md-4 picture">
                <a data-fancybox="single" class="fancybox" href="/mediafiles/{{ product.image }}">
                    <img class="center-block" src="{% if product.image %}/mediafiles/{{ product.image}}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
                </a>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-8 title_desc">

                <p class="zagolovok">{{ product.title_en }}</p>
                <hr>
                <p id="interes">Did you like our product? Leave your number and we'll call you back.</p>
                <div class="zakaz_zvonka">
                    <p id="hata"></p>
                    <form method="post" action="{% url 'product:send_number' %}" id="myForm">
                        {% csrf_token %}
                        <input class="nomer" name="number" placeholder="0555123456">
                        <button class="otpravka" type="submit">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid product_second">
    <div class="row sotka">
        <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 product_second_block">
            <p>{{ product.full_description_en| safe | linebreaks }}</p>
            <a href="{% url 'product:product-list-en' %}#products">
                <span class="visible-xs" id="for_tel">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i>
                    Назад
                </span>
            </a>
        </div>
    </div>
</div>

<div class="container-fluid footer">
    <div class="row">
        <div class="text-center">
            <div class="col-md-4">
                <p>
                    <span>
                        <i class="fa fa-map-marker mesto" aria-hidden="true"></i>
                    </span>
                    Tynystanov str., 197/1
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <span id="cep">                         <i class="fa fa-phone-square"></i>                         + 996 505 04 07 17<br/> 		        <i class="fa fa-whatsapp" style="color:#25d366"></i> 		        + 90 507 728 66 86                     </span>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <span>
                        Follow us:
                        <i class="fa fa-facebook"></i>
                        <i class="fa fa-instagram"></i>
                    </span>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid rights">
    <div class="row">
        <div class="col-md-12">
            <p>&#169; 2020 DEVALA. All rights reserved</p>
        </div>
    </div>
</div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close text-center" data-dismiss="modal">&times;</button>

      </div>
      <div class="modal-body text-center">
        <h4 class="modal-title">Your number has been successfully sent!</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript" src="{% static 'js/ajaxform.js' %}"></script>
<script>
    $(document).ready(function() {
            // bind 'myForm' and provide a simple callback function
            $('#myForm').ajaxForm(function(response) {
                console.log(response);
                if (response['error']) {
                    $('input').addClass('has-errors');
                    $('#hata').html('Your number is wrong').slideUp().slideDown();
                }
                else {
                    $('input:not([name="csrfmiddlewaretoken"])').val('');
                    $('#hata').css('display', 'none').html('');
                    $('input').removeClass('has-errors');
                    $('#myModal').modal();
                }
            });
        });
</script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- BEGIN JIVOSITE CODE {literal} --> <script type='text/javascript'> (function(){ var widget_id = '9a3knLkEuT';var d=document;var w=window;function l(){ var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);}if(d.readyState=='complete'){l();}else{if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();</script> <!-- {/literal} END JIVOSITE CODE -->
</body>
</html>

app/templates/products/details_kg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.title_kg }}</title>
    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fancybox-3.0/dist/jquery.fancybox.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'responsive/main_responsive.css' %}">
    <script src="{% static 'fancybox-3.0/dist/jquery.fancybox.min.js' %}"></script>
</head>
<body class="details">
<div>
<div class="container-fluid hat compensate-for-scrollbar">
    <div class="row">
        <a href="{% url 'product:product-list-kg' %}#products">
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-3 col-xl-3 text-center">
                <p class="shapka">
                    <span>
                        <i class="fa fa-chevron-left" aria-hidden="true"></i>
                        Артка
                    </span>
                </p>
            </div>
        </a>
        <div class="col-xs-5 col-sm-4 col-md-6 col-lg-6 col-xl-6 text-center">
{#            <img src="{% static 'img/devala.png' %}" height="40" width="auto" >#}
        </div>
        <div class="col-xs-7 col-sm-4 col-md-3 col-lg-3 col-xl-3 text-center"><i></i>
            <p class="shapka">
                <span>
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    0505040717
                </span>
            </p>
        </div>
    </div>
</div>

<div class="container-fluid product_main">
    <div class="row sotka">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2 col-xl-8 col-xl-offset-2 product_main_block">
            <div class="col-sm-12 col-md-4 picture">
                <a data-fancybox="single" class="fancybox" href="/mediafiles/{{ product.image }}">
                    <img class="center-block" src="{% if product.image %}/mediafiles/{{ product.image}}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
                </a>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-8 title_desc">

                <p class="zagolovok">{{ product.title_kg }}</p>
                <hr>
                <p id="interes">Кызыктыңызбы? Номер таштаңыз, биз байланышабыз</p>
                <div class="zakaz_zvonka">
                    <p id="hata"></p>
                    <form method="post" action="{% url 'product:send_number' %}" id="myForm">
                        {% csrf_token %}
                        <input class="nomer" name="number" placeholder="0555123456">
                        <button class="otpravka" type="submit">Жөнөтүү</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid product_second">
    <div class="row sotka">
        <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 product_second_block">
            <p>{{ product.full_description_kg| safe | linebreaks }}</p>

            <a href="{% url 'product:product-list-kg' %}#products">
                <span class="visible-xs" id="for_tel">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i>
                    Артка
                </span>
            </a>
        </div>
    </div>
</div>

<div class="container-fluid footer">
    <div class="row">
        <div class="text-center">
            <div class="col-md-4">
                <p>
                    <span>
                        <i class="fa fa-map-marker mesto" aria-hidden="true"></i>
                    </span>
                    Тыныстанов к., 197
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <span id="cep">                         <i class="fa fa-phone-square"></i>                         + 996 505 04 07 17<br/> 		        <i class="fa fa-whatsapp" style="color:#25d366"></i> 		        + 90 507 728 66 86                     </span>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <span>
                        Биздин соц тармактарыбыз:
                        <i class="fa fa-facebook"></i>
                        <i class="fa fa-instagram"></i>
                    </span>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid rights">
    <div class="row">
        <div class="col-md-12">
            <p>&#169; 2020 DEVALA. Бардык укуктар корголгон</p>
        </div>
    </div>
</div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close text-center" data-dismiss="modal">&times;</button>

      </div>
      <div class="modal-body text-center">
        <h4 class="modal-title">Номериңиз жөнөтүлдү!</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Жабуу</button>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript" src="{% static 'js/ajaxform.js' %}"></script>
<script>
    $(document).ready(function() {
            // bind 'myForm' and provide a simple callback function
            $('#myForm').ajaxForm(function(response) {
                console.log(response);
                if (response['error']) {
                    $('input').addClass('has-errors');
                    $('#hata').html('Номериңиз туура эмес').slideUp().slideDown();
                }
                else {
                    $('input:not([name="csrfmiddlewaretoken"])').val('');
                    $('#hata').css('display', 'none').html('');
                    $('input').removeClass('has-errors');
                    $('#myModal').modal();
                }
            });
        });
</script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- BEGIN JIVOSITE CODE {literal} --> <script type='text/javascript'> (function(){ var widget_id = '9a3knLkEuT';var d=document;var w=window;function l(){ var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);}if(d.readyState=='complete'){l();}else{if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();</script> <!-- {/literal} END JIVOSITE CODE -->
</body>
</html>